### ISSUE TITLE
You can beautify the code.

### ISSUE THREAD

**Issue by RaminMammadzada** [Prabhakarzx/AlexAndPrabhakar-NYTimes-Clone#1]
You can use a beautifier plugins to beautify your HTML and CSS. So your code will well aligned. In that way, the people who will check your code can read it easily.

**Comment by Prabhakarzx** [comment]
Thank you @RaminMammadzada for the suggestion!
Beautify is successfully added and applied on files and it do arrange the code better and readable!
**Thanks!**
